### ISSUE TITLE
Recommendation: Change string unit for radian to the SI standard of `rad`

### ISSUE THREAD

**Issue by vitalielias** [kit-data-manager/Metadata-Schemas-for-Materials-Science#7]
The BIPD who developed the international system of units declared `rad` as the proper symbol for radian ([see Table 4 in their official publication, p. 137](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf/2d2b50bf-f2b4-9661-f402-5f9d66e4b507?version=1.12&t=1685993350255&download=true)). Since all other (SI) units are written using their symbol, I would recommend the same be done for dimensional angles.

I understand that radian is probably written with its full name to stay consistent with "degree", given that the recognized symbol for degrees is not user- or code-friendly, however degree is not an SI unit, so there exists that distinction.

I thought I would just write this up to see your thoughts :)

**Comment by reetuelzajoseph** [comment]
I see your point. But as "rad" would be displayed along with "degree", I think it makes more sense to keep the whole "radian". Also we were never limiting to SI units. We have things like cm3/min or keV which are not SI units. In all the schemas we provide all possible kinds of units. It is just that for Thermo Fisher instruments, they don't contain the units like in Zeiss, but the units for their values are generally SI. Again in case of landing energy they do not use SI, which was inconsistent.

**Comment by reetuelzajoseph** [comment]
we could add "rad" as one of the acceptable values. Then the schema would work well. The issue here would be that the metadata editor would then display rad, along with radian and degree, which would look funny. Can't you just add a line that says, if the unit is rad, change it to radian?

**Comment by vitalielias** [comment]
I agree having both `rad` and `radian` isn't a good solution, and probably defeats the purpose of having a schema in the first place. 

> Can't you just add a line that says, if the unit is rad, change it to radian?

I very easily can, but that's not the point I guess. It's a good solution in the interim, just wanted to open the discussion and see what you thought, but I totaly see what you mean and why it is the way that it is!
